"""Initialize and populate the shared AI model library.

The script performs network downloads only through the explicit ``download`` command.
It never installs runtimes or Python packages.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import UTC, datetime
from pathlib import Path, PurePosixPath
from types import TracebackType
from typing import Any, Self
from uuid import uuid4

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPOSITORY_ROOT / "src"
if str(SOURCE_ROOT) not in sys.path:
    sys.path.insert(0, str(SOURCE_ROOT))

from aiopenstudio.core.model_library import (  # noqa: E402
    ArtifactKind,
    DownloadManifest,
    DownloadProvider,
    DownloadSpec,
    InstalledArtifact,
    ModelLibrarySettings,
)
from aiopenstudio.infrastructure.database.model_library_catalog import (  # noqa: E402
    ModelLibraryCatalog,
)

DEFAULT_ROOT = Path("data/models")
DEFAULT_MANIFEST = REPOSITORY_ROOT / "models" / "download-catalog.json"
DEFAULT_SCHEMA = REPOSITORY_ROOT / "schemas" / "model-library.sql"
DEFAULT_ENV_FILE = REPOSITORY_ROOT / ".env"
ENV_BEGIN = "# BEGIN SHARED MODEL LIBRARY"
ENV_END = "# END SHARED MODEL LIBRARY"


class DownloadError(RuntimeError):
    """An expected provider or download failure."""


def load_manifest(path: Path) -> DownloadManifest:
    return DownloadManifest.model_validate_json(path.read_text(encoding="utf-8"))


def build_settings(root: Path, env_file: Path) -> ModelLibrarySettings:
    return ModelLibrarySettings(_env_file=env_file, model_library_root=root.resolve())


def initialize_library(
    settings: ModelLibrarySettings,
    catalog: ModelLibraryCatalog,
    manifest_path: Path,
    env_file: Path,
) -> None:
    settings.model_library_root.mkdir(parents=True, exist_ok=True)
    for directory in settings.managed_directories:
        directory.mkdir(parents=True, exist_ok=True)
    catalog.initialize()
    destination = settings.resolve(settings.model_manifests_dir) / manifest_path.name
    shutil.copy2(manifest_path, destination)
    update_env_file(env_file, settings)


def update_env_file(env_file: Path, settings: ModelLibrarySettings) -> None:
    env_file.parent.mkdir(parents=True, exist_ok=True)
    existing = env_file.read_text(encoding="utf-8") if env_file.exists() else ""
    root = settings.model_library_root.resolve()
    values = {
        "AIOPENSTUDIO_MODEL_LIBRARY_ROOT": root.as_posix(),
        "AIOPENSTUDIO_MODEL_CATALOG_PATH": settings.model_catalog_path.as_posix(),
        "AIOPENSTUDIO_OLLAMA_MODELS_DIR": settings.ollama_models_dir.as_posix(),
        "AIOPENSTUDIO_HUGGINGFACE_HOME": settings.huggingface_home.as_posix(),
        "AIOPENSTUDIO_WHISPER_MODELS_DIR": settings.whisper_models_dir.as_posix(),
        "AIOPENSTUDIO_FOOOCUS_MODELS_DIR": settings.fooocus_models_dir.as_posix(),
        "AIOPENSTUDIO_EMBEDDING_MODELS_DIR": settings.embedding_models_dir.as_posix(),
        "AIOPENSTUDIO_MODEL_MANIFESTS_DIR": settings.model_manifests_dir.as_posix(),
        "AIOPENSTUDIO_MODEL_CACHE_DIR": settings.model_cache_dir.as_posix(),
        "AIOPENSTUDIO_MODEL_TEMP_DIR": settings.model_temp_dir.as_posix(),
        "AIOPENSTUDIO_MODEL_CHECKLIST_PATH": settings.model_checklist_path.as_posix(),
        "AIOPENSTUDIO_WEIGHTS_DIR": root.as_posix(),
        "OLLAMA_MODELS": settings.resolve(settings.ollama_models_dir).as_posix(),
        "HF_HOME": settings.resolve(settings.huggingface_home).as_posix(),
    }
    block = "\n".join(
        [ENV_BEGIN, "# Generated by scripts/model_library.py; dynamic model state lives in SQLite."]
        + [f"{key}={value}" for key, value in values.items()]
        + [ENV_END]
    )
    if ENV_BEGIN in existing and ENV_END in existing:
        prefix, remainder = existing.split(ENV_BEGIN, maxsplit=1)
        _, suffix = remainder.split(ENV_END, maxsplit=1)
        existing = f"{prefix.rstrip()}\n{suffix.lstrip()}"

    managed_assignments = tuple(f"{key}=" for key in values)
    preserved_lines = [
        line for line in existing.splitlines() if not line.startswith(managed_assignments)
    ]
    preserved = "\n".join(preserved_lines).strip()
    if preserved:
        updated = f"{preserved}\n\n{block}\n"
    else:
        updated = f"{block}\n"
    env_file.write_text(updated, encoding="utf-8")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(8 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def directory_size(path: Path) -> int:
    return sum(
        item.stat().st_size
        for item in path.rglob("*")
        if item.is_file() and ".cache" not in item.parts
    )


def format_bytes(value: int | None) -> str:
    if value is None:
        return "desconocido"
    amount = float(value)
    for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
        if amount < 1024 or unit == "TiB":
            return f"{amount:.1f} {unit}"
        amount /= 1024
    raise AssertionError("unreachable")


def download_http_file(
    spec: DownloadSpec,
    settings: ModelLibrarySettings,
    force: bool,
) -> dict[str, Any]:
    destination = settings.resolve(Path(*spec.local_path.parts))
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists() and not force:
        return {
            "size_bytes": destination.stat().st_size,
            "checksum_sha256": sha256_file(destination),
            "revision": spec.revision,
            "metadata": {"reused_existing_file": True},
        }

    partial = destination.with_name(f"{destination.name}.partial")
    offset = partial.stat().st_size if partial.exists() else 0
    request = urllib.request.Request(spec.source)
    if offset:
        request.add_header("Range", f"bytes={offset}-")
    print(f"  HTTP: {spec.source}")
    print(f"  Destino: {destination}")
    try:
        response = urllib.request.urlopen(request, timeout=60)  # noqa: S310
    except (urllib.error.URLError, TimeoutError) as error:
        raise DownloadError(str(error)) from error
    with response:
        append = offset > 0 and response.status == 206
        if not append:
            offset = 0
        total_header = response.headers.get("Content-Length")
        total = offset + int(total_header) if total_header else None
        mode = "ab" if append else "wb"
        downloaded = offset
        last_report = time.monotonic()
        with partial.open(mode) as stream:
            while chunk := response.read(8 * 1024 * 1024):
                stream.write(chunk)
                downloaded += len(chunk)
                if time.monotonic() - last_report >= 2:
                    suffix = f" / {format_bytes(total)}" if total else ""
                    print(f"  {format_bytes(downloaded)}{suffix}", flush=True)
                    last_report = time.monotonic()
    os.replace(partial, destination)
    return {
        "size_bytes": destination.stat().st_size,
        "checksum_sha256": sha256_file(destination),
        "revision": spec.revision,
        "metadata": {"resumed": offset > 0},
    }


def download_huggingface(
    spec: DownloadSpec,
    settings: ModelLibrarySettings,
    force: bool,
) -> dict[str, Any]:
    try:
        from huggingface_hub import HfApi, snapshot_download
    except ImportError as error:
        raise DownloadError(
            "Falta huggingface-hub. Instala las dependencias 'models' del proyecto."
        ) from error

    destination = settings.resolve(Path(*spec.local_path.parts))
    destination.mkdir(parents=True, exist_ok=True)
    token = os.environ.get("HF_TOKEN")
    requested_revision = spec.revision or "main"
    try:
        model_info = HfApi(token=token).model_info(spec.source, revision=requested_revision)
        resolved_revision = model_info.sha
        if not resolved_revision:
            raise DownloadError(f"Hugging Face no devolvió una revisión para {spec.source}")
        print(f"  Hugging Face: {spec.source}@{resolved_revision}")
        snapshot_download(
            repo_id=spec.source,
            revision=resolved_revision,
            local_dir=destination,
            cache_dir=settings.resolve(settings.huggingface_home) / "hub",
            token=token,
            force_download=force,
        )
    except Exception as error:
        if isinstance(error, DownloadError):
            raise
        raise DownloadError(str(error)) from error
    return {
        "size_bytes": directory_size(destination),
        "checksum_sha256": None,
        "revision": resolved_revision,
        "metadata": {"revision_resolved": True},
    }


class OllamaSession:
    """Own a temporary loopback Ollama server with a controlled model root."""

    STARTUP_TIMEOUT_SECONDS = 90

    def __init__(self, settings: ModelLibrarySettings, host: str = "127.0.0.1:11435") -> None:
        self.settings = settings
        self.host = host
        self.base_url = f"http://{host}"
        self.process: subprocess.Popen[str] | None = None
        self.log_stream: Any = None
        self.environment = os.environ.copy()
        self.environment.update(
            {
                "OLLAMA_HOST": host,
                "OLLAMA_MODELS": settings.resolve(settings.ollama_models_dir).as_posix(),
                "OLLAMA_NO_CLOUD": "true",
                "OLLAMA_MAX_LOADED_MODELS": "1",
                "OLLAMA_NUM_PARALLEL": "1",
            }
        )

    def __enter__(self) -> Self:
        executable = shutil.which("ollama")
        if executable is None:
            raise DownloadError("Ollama no está instalado o no está disponible en PATH")
        if self._is_ready():
            raise DownloadError(
                f"El puerto privado {self.host} ya está ocupado; "
                "no se puede garantizar OLLAMA_MODELS"
            )
        log_path = (
            self.settings.resolve(self.settings.model_temp_dir) / "ollama-download-server.log"
        )
        log_path.parent.mkdir(parents=True, exist_ok=True)
        self.log_stream = log_path.open("a", encoding="utf-8")
        creation_flags = subprocess.CREATE_NO_WINDOW if sys.platform == "win32" else 0
        self.process = subprocess.Popen(
            [executable, "serve"],
            env=self.environment,
            stdout=self.log_stream,
            stderr=subprocess.STDOUT,
            text=True,
            creationflags=creation_flags,
        )
        try:
            deadline = time.monotonic() + self.STARTUP_TIMEOUT_SECONDS
            while time.monotonic() < deadline:
                if self.process.poll() is not None:
                    raise DownloadError(f"Ollama terminó durante el arranque; revisa {log_path}")
                if self._is_ready():
                    return self
                time.sleep(0.5)
            raise DownloadError(
                f"Ollama no respondió dentro de {self.STARTUP_TIMEOUT_SECONDS} segundos; "
                f"revisa {log_path}"
            )
        except BaseException:
            self._close()
            raise

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        self._close()

    def _close(self) -> None:
        if self.process and self.process.poll() is None:
            self.process.terminate()
            try:
                self.process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                self.process.kill()
                self.process.wait(timeout=5)
        if self.log_stream:
            self.log_stream.close()

    def pull(self, spec: DownloadSpec) -> dict[str, Any]:
        executable = shutil.which("ollama")
        if executable is None:
            raise DownloadError("Ollama dejó de estar disponible en PATH")
        print(f"  Ollama: {spec.runtime_reference}")
        result = subprocess.run(
            [executable, "pull", spec.runtime_reference or spec.source],
            env=self.environment,
            check=False,
        )
        if result.returncode != 0:
            raise DownloadError(f"ollama pull terminó con código {result.returncode}")
        model = self._find_model(spec.runtime_reference or spec.source)
        digest = str(model.get("digest", ""))
        checksum = digest.removeprefix("sha256:") if digest.startswith("sha256:") else None
        if checksum is not None and len(checksum) != 64:
            checksum = None
        return {
            "size_bytes": int(model["size"]) if model.get("size") is not None else None,
            "checksum_sha256": checksum,
            "revision": digest or None,
            "metadata": {"ollama_name": str(model.get("name", spec.source))},
        }

    def _is_ready(self) -> bool:
        try:
            with urllib.request.urlopen(f"{self.base_url}/api/version", timeout=1):  # noqa: S310
                return True
        except (urllib.error.URLError, TimeoutError):
            return False

    def _find_model(self, requested: str) -> dict[str, Any]:
        try:
            with urllib.request.urlopen(f"{self.base_url}/api/tags", timeout=10) as response:  # noqa: S310
                payload = json.load(response)
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as error:
            raise DownloadError(f"No se pudo verificar el modelo en Ollama: {error}") from error
        candidates = payload.get("models", [])
        normalized = requested.casefold()
        for model in candidates:
            names = {str(model.get("name", "")).casefold(), str(model.get("model", "")).casefold()}
            if normalized in names:
                return dict(model)
        raise DownloadError(f"Ollama completó el pull pero {requested!r} no aparece en /api/tags")


def installed_artifact(spec: DownloadSpec, result: dict[str, Any]) -> InstalledArtifact:
    now = datetime.now(UTC)
    return InstalledArtifact(
        artifact_id=spec.artifact_id,
        display_name=spec.display_name,
        kind=spec.kind,
        provider=spec.provider,
        family=spec.family,
        variant=spec.variant,
        quantization=spec.quantization,
        source=spec.source,
        source_url=spec.source_url,
        revision=result.get("revision"),
        runtime_reference=spec.runtime_reference,
        relative_path=PurePosixPath(spec.local_path),
        license_name=spec.license_name,
        license_url=spec.license_url,
        size_bytes=result.get("size_bytes"),
        checksum_sha256=result.get("checksum_sha256"),
        capabilities=spec.capabilities,
        installed_at=now,
        verified_at=now,
        metadata=result.get("metadata", {}),
    )


def write_checklist(
    settings: ModelLibrarySettings,
    manifest: DownloadManifest,
    catalog: ModelLibraryCatalog,
) -> None:
    installed = {artifact.artifact_id: artifact for artifact in catalog.list()}
    latest_events = catalog.latest_events()
    lines = [
        "# Checklist temporal de descargas",
        "",
        f"Actualizado: {datetime.now(UTC).isoformat()}",
        "",
        "Este archivo es generado. SQLite es la fuente de verdad para instalaciones exitosas.",
        "",
        "| Listo | Artefacto | Tipo | Proveedor | Tamaño | Estado | Ruta relativa |",
        "|---|---|---|---|---:|---|---|",
    ]
    for spec in manifest.artifacts:
        artifact = installed.get(spec.artifact_id)
        event_status, event_detail = latest_events.get(spec.artifact_id, ("pendiente", None))
        status = "instalado" if artifact else event_status
        if event_detail and not artifact:
            status = f"{status}: {event_detail.replace('|', '/')}"
        size = artifact.size_bytes if artifact else spec.expected_size_bytes
        row_template = (
            "| {checked} | `{artifact_id}` | {kind} | {provider} | {size} | "
            "{status} | `{path}` |"
        )
        lines.append(
            row_template.format(
                checked="[x]" if artifact else "[ ]",
                artifact_id=spec.artifact_id,
                kind=spec.kind.value,
                provider=spec.provider.value,
                size=format_bytes(size),
                status=status,
                path=spec.local_path.as_posix(),
            )
        )
    settings.checklist_file.write_text("\n".join(lines) + "\n", encoding="utf-8")


def select_artifacts(
    args: argparse.Namespace,
    manifest: DownloadManifest,
) -> tuple[DownloadSpec, ...]:
    by_id = {artifact.artifact_id: artifact for artifact in manifest.artifacts}
    if args.all:
        selected = list(manifest.artifacts)
    elif args.kind:
        selected = [artifact for artifact in manifest.artifacts if artifact.kind.value == args.kind]
    elif args.artifact_ids:
        unknown = sorted(set(args.artifact_ids) - by_id.keys())
        if unknown:
            raise DownloadError(f"Artefactos desconocidos: {', '.join(unknown)}")
        selected = [by_id[artifact_id] for artifact_id in args.artifact_ids]
    else:
        raise DownloadError("Indica IDs, --kind o --all")
    return tuple(selected)


def confirm_download(selected: tuple[DownloadSpec, ...], assume_yes: bool) -> None:
    expected = sum(item.expected_size_bytes or 0 for item in selected)
    print(f"Artefactos seleccionados: {len(selected)}")
    print(f"Tamaño conocido aproximado: {format_bytes(expected)}")
    for item in selected:
        print(f"  - {item.artifact_id}: {item.license_name}")
    if assume_yes:
        return
    answer = input("Escribe DESCARGAR para aceptar las fuentes/licencias indicadas: ").strip()
    if answer != "DESCARGAR":
        raise DownloadError("Descarga cancelada")


def run_downloads(
    selected: tuple[DownloadSpec, ...],
    settings: ModelLibrarySettings,
    catalog: ModelLibraryCatalog,
    env_file: Path,
    *,
    force: bool,
    fail_fast: bool,
) -> int:
    run_id = uuid4().hex
    failures = 0
    ollama_specs = [item for item in selected if item.provider is DownloadProvider.OLLAMA]
    other_specs = [item for item in selected if item.provider is not DownloadProvider.OLLAMA]

    def process(spec: DownloadSpec, ollama: OllamaSession | None = None) -> None:
        nonlocal failures
        if catalog.get(spec.artifact_id) is not None and not force:
            print(f"[omitido] {spec.artifact_id}: ya está registrado")
            catalog.record_event(run_id, spec.artifact_id, "skipped", "already installed")
            return
        print(f"[inicio] {spec.artifact_id} — {spec.display_name}")
        catalog.record_event(run_id, spec.artifact_id, "started")
        try:
            if spec.provider is DownloadProvider.OLLAMA:
                if ollama is None:
                    raise DownloadError("La sesión Ollama no está disponible")
                result = ollama.pull(spec)
            elif spec.provider is DownloadProvider.HUGGINGFACE:
                result = download_huggingface(spec, settings, force)
            else:
                result = download_http_file(spec, settings, force)
            artifact = installed_artifact(spec, result)
            catalog.save(artifact)
            catalog.record_event(run_id, spec.artifact_id, "installed")
            update_env_file(env_file, settings)
            print(f"[instalado] {spec.artifact_id}: {format_bytes(artifact.size_bytes)}")
        except Exception as error:
            failures += 1
            detail = str(error).replace("\n", " ")[:1000]
            catalog.record_event(run_id, spec.artifact_id, "failed", detail)
            print(f"[falló] {spec.artifact_id}: {detail}", file=sys.stderr)
            if fail_fast:
                raise

    if ollama_specs:
        try:
            with OllamaSession(settings) as ollama:
                for spec in ollama_specs:
                    process(spec, ollama)
        except Exception as error:
            pending = [item for item in ollama_specs if catalog.get(item.artifact_id) is None]
            for spec in pending:
                failures += 1
                detail = str(error).replace("\n", " ")[:1000]
                catalog.record_event(run_id, spec.artifact_id, "failed", detail)
                print(f"[falló] {spec.artifact_id}: {detail}", file=sys.stderr)
            if fail_fast:
                return 1
    for spec in other_specs:
        try:
            process(spec)
        except Exception:
            return 1
    return 1 if failures else 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--env-file", type=Path, default=DEFAULT_ENV_FILE)
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("init", help="Crear carpetas, SQLite, .env y checklist sin descargar")

    list_parser = subparsers.add_parser("list", help="Listar candidatos del manifiesto")
    list_parser.add_argument("--kind", choices=[kind.value for kind in ArtifactKind])

    subparsers.add_parser("status", help="Mostrar instalaciones registradas y regenerar checklist")

    download_parser = subparsers.add_parser("download", help="Descargar artefactos explícitos")
    download_parser.add_argument("artifact_ids", nargs="*")
    selection = download_parser.add_mutually_exclusive_group()
    selection.add_argument("--kind", choices=[kind.value for kind in ArtifactKind])
    selection.add_argument("--all", action="store_true")
    download_parser.add_argument("--yes", action="store_true", help="No pedir confirmación")
    download_parser.add_argument("--force", action="store_true", help="Revalidar o redescargar")
    download_parser.add_argument("--fail-fast", action="store_true")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    manifest = load_manifest(args.manifest)
    settings = build_settings(args.root, args.env_file)
    catalog = ModelLibraryCatalog(settings.catalog_file, args.schema)

    if args.command == "list":
        artifacts = manifest.artifacts
        if args.kind:
            artifacts = tuple(item for item in artifacts if item.kind.value == args.kind)
        for item in artifacts:
            print(
                f"{item.artifact_id:<45} {item.provider.value:<12} "
                f"{format_bytes(item.expected_size_bytes):>12}  {item.display_name}"
            )
        return 0

    initialize_library(settings, catalog, args.manifest, args.env_file)
    if args.command == "init":
        write_checklist(settings, manifest, catalog)
        print(f"Biblioteca inicializada en: {settings.model_library_root}")
        print(f"Catálogo SQLite: {settings.catalog_file}")
        print(f"Checklist: {settings.checklist_file}")
        return 0
    if args.command == "status":
        write_checklist(settings, manifest, catalog)
        installed = catalog.list()
        print(f"Instalados: {len(installed)}")
        for artifact in installed:
            print(f"  - {artifact.artifact_id}: {format_bytes(artifact.size_bytes)}")
        return 0

    try:
        selected = select_artifacts(args, manifest)
        confirm_download(selected, args.yes)
    except DownloadError as error:
        print(f"Error: {error}", file=sys.stderr)
        return 2
    result = run_downloads(
        selected,
        settings,
        catalog,
        args.env_file,
        force=args.force,
        fail_fast=args.fail_fast,
    )
    write_checklist(settings, manifest, catalog)
    return result


if __name__ == "__main__":
    raise SystemExit(main())
